### ISSUE TITLE
bin/setup fail due to db migration fail

### ISSUE THREAD

**Issue by Gutopro** [sustainable-rails/sustainable-rails-docker#15]
Hello i'm new to Rails and "sustainable web development with RoR" was recommended for me, i must say it's such an interesting book. when managing runtime configuration after deleting the 3 files in the config directory and installing the dotenv gem i ran "bin/setup" and got this error 
![todays work](https://github.com/sustainable-rails/sustainable-rails-docker/assets/111025771/9c8c6294-1150-4b13-b0c2-dfa76dd4d2cb)
getting so much output on my screen scared me at first and i couldn't seem to grasp what went wrong, after much research i discovered that the issue was due to the fact that dotenv wasn't loaded in the "config/application.rb" file, after doing this my bin/setup loaded without the error. could there be away where this step is mentioned, to help other newbies like me? it would aslo save time as i spent a considerable amount of it trying to fix the issue. thank you so much for this book, the world is a better place because of it.

**Comment by davetron5000** [comment]
That is odd - you should not have to require dotenv explicitly like that, as long as you are using bundler to run everything.

When you have this in your `Gemfile`:

```ruby
gem "dotenv-rails"
```

Bundler will automatically run code like `require "dotenv-rails"` for you, as long as whatever you are doing uses bundler, and `bin/setup` is using bundler appropriately (whenever I build the book PDF, it runs all the code locally and wont' build the book until the code works).

I'd be happy to take a look if your app is on GitHub somewhere?

## Details about how this all works

The `bin/setup` script should use bundler, since it ultimately does:

* `bundle install`
* `bin/rails db:reset` (`bin/rails` is a "binstub" that basically does `bundle exec rails` - `bundle exec` being the most basic way to run things with bundler)

Looking at the error (yes, that is sadly typical - it's trying to give you a ton of context, but it can be really hard to see what the actual problem is), the very last line tells you what `bin/setup` was trying to do:

```
[ bin/setup ] [ "bin/rails db:reset || bin/rails db:migrate" ] failed
```

To find out *why*, you have to look through all that wall of text.  One part that jumps out is this:

```
URI::InvalidURIError: bad URI(is not a URI?): ''
```

This is a pretty hard-to-understand error message, but my guess would be that Rails is trying to parse your `DATABASE_URL` with Ruby's builtin library and getting this failure.  the empty string tells me that it couldn't find your DATABASE_URL and got the empty string or `nil` somewhere.

So this definitely tracks with your finding that dotenv didn't load itself automatically

**Comment by Gutopro** [comment]
thanks @davetron5000 here's a link to my app: https://github.com/Gutopro/event-app

**Comment by Gutopro** [comment]
thanks it's been fixed.

**Comment by mikesklein** [comment]
I also ran into this issue. To fix it I added the following to the top of the setup file.

require 'dotenv'
Dotenv.load('.env.development', '.env.test')
