### ISSUE TITLE
rails new failing

### ISSUE THREAD

**Issue by joelcahalan** [sustainable-rails/sustainable-rails-docker#2]
After cloning, building, starting and running bin/exec bash, the rails new command errors. 
<img width="1004" alt="Screen Shot 2020-04-07 at 4 33 06 PM" src="https://user-images.githubusercontent.com/55459818/78717503-b906c680-78ee-11ea-876e-bad39198db8f.png">

**Comment by davetron5000** [comment]
The error that is causing `rails new` to exit is `invalid option -=`.  The other errors from bundler are just warnings, but I'm not sure what they mean or if they matter.  And I think they just started happening recently like maybe even today.

Fix forthcoming…

**Comment by davetron5000** [comment]
Fixed in 812308aa1b52a0d0f817a73f33426737ed3636a0

You'll need to re-run `bin/build` which will take a while.

Also as mentioned, I'm not sure why bundler is doing what it's doing.  I had found an old issue that said `gem update --system` would fix it, though things are updated inside the Docker container already.  When I went into the newly generated rails app and did `bundle binstubs --all` it did work with no errors.  No clue what's going on, but will dig deeper before the next release (and update to Ruby 2.7.1)
